powershell -f ..\powershell-deployer\deployer.ps1 deploy-tgt-tskgrp-01.json $args[0] $args[1] $args[2] $args[3] $args[4] $args[5] $args[6] $args[7]
powershell -f ..\powershell-deployer\deployer.ps1 deploy-tgt-tskgrp-02.json $args[0] $args[1] $args[2] $args[3] $args[4] $args[5] $args[6] $args[7]
powershell -f ..\powershell-deployer\deployer.ps1 deploy-tgt-tskgrp-03.json $args[0] $args[1] $args[2] $args[3] $args[4] $args[5] $args[6] $args[7]
powershell -f ..\powershell-deployer\deployer.ps1 deploy-tgt-tskgrp-04.json $args[0] $args[1] $args[2] $args[3] $args[4] $args[5] $args[6] $args[7]
powershell -f ..\powershell-deployer\deployer.ps1 deploy-tgt-tskgrp-05.json $args[0] $args[1] $args[2] $args[3] $args[4] $args[5] $args[6] $args[7]
powershell -f ..\powershell-deployer\deployer.ps1 deploy-tgt-tskgrp-06.json $args[0] $args[1] $args[2] $args[3] $args[4] $args[5] $args[6] $args[7]