CREATE LOGIN [user_1] WITH PASSWORD = 'Password@123'; /* S: SQL_LOGIN */
CREATE LOGIN [user_2] WITH PASSWORD = 'Password@123'; /* S: SQL_LOGIN */
CREATE LOGIN [user_3] WITH PASSWORD = 'Password@123'; /* S: SQL_LOGIN */
CREATE LOGIN [user_4] WITH PASSWORD = 'Password@123'; /* S: SQL_LOGIN */
CREATE LOGIN [user_5] WITH PASSWORD = 'Password@123'; /* S: SQL_LOGIN */
CREATE LOGIN [user_6] WITH PASSWORD = 'Password@123'; /* S: SQL_LOGIN */

GO

